### ISSUE TITLE
(2026, 'SSL connection error: unknown error number')

### ISSUE THREAD

**Issue by frakman1** [Ducatel/reviewboard#1]
I ran the three docker commands in turn:
```bash
docker run -d --name database -e MYSQL_ROOT_PASSWORD=reviewboard -e MYSQL_USER=reviewboard -e MYSQL_PASSWORD=reviewboard -e MYSQL_DATABASE=reviewboard mysql
docker run -d --name cache memcached
docker run -d --name reviewboard -p "8000:8000" --link "cache:memcached" --link "database:rb_db" ducatel/reviewboard
```

... but when I browse to `127.0.0.1:8000`, I get this error:

![image](https://user-images.githubusercontent.com/5826484/82070980-7382a980-96a3-11ea-8dcf-e90f174fcfb5.png)

Full docker logs [here](https://pastebin.com/hb3cJJXX) 

```ERROR:root:Could not load siteconfig: (2026, 'SSL connection error: unknown error number')
CRITICAL:root:Unable to load SiteConfiguration: (2026, 'SSL connection error: unknown error number')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/reviewboard/admin/middleware.py", line 44, in process_request
    siteconfig = SiteConfiguration.objects.get_current()
  File "/usr/local/lib/python2.7/dist-packages/djblets/siteconfig/managers.py", line 42, in get_current
    return self.get_for_site_id(Site.objects.get_current().pk)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sites/models.py", line 47, in get_current
    current_site = self.get(pk=sid)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 304, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 857, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 713, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 162, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 132, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 115, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 435, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (2026, 'SSL connection error: unknown error number')
```

I don't need SSL as this is an internal test. Is there a way to disable SSL wherever it needs to be (either in mysql or reviewboard)?

**Comment by Eason-YC-Huang** [comment]
@frakman1 Have you found a way to fix this ? I have the same problem now   /(ㄒoㄒ)/~~

**Comment by frakman1** [comment]
@hexffff0 Nope.
@Ducatel  Ducatel Do you have any insight about this?

**Comment by Lozerd** [comment]
I'm no pro at configuring databases, but after reading numerous forums and articles, I solved this issue by skipping ssl in MySQL**.ini file.

Here's the article i've found: https://blog.csdn.net/weixin_44065501/article/details/124018738
If link doesn't work, just add "skip_ssl" under [mysqld] section in your MySQL**.ini
